package cli.utils.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static cli.utils.Util.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.24 15:14:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UtilTest {



  // Generated by ComTest BEGIN
  /** testParseAuthor37 */
  @Test
  public void testParseAuthor37() {    // Util: 37
    String[] s1 = parseAuthor("Leary, Timothy Francis, 1920-1996, kirjoittaja"); 
    assertEquals("From: Util line: 39", "Leary, Timothy Francis", s1[0]); 
    assertEquals("From: Util line: 40", "1920", s1[1]); 
    assertEquals("From: Util line: 41", "1996", s1[2]); 
    String[] s2 = parseAuthor("Forss, Timo Kalevi, 1967- kirjoittaja"); 
    assertEquals("From: Util line: 43", "Forss, Timo Kalevi", s2[0]); 
    assertEquals("From: Util line: 44", "1967", s2[1]); 
    assertEquals("From: Util line: 45", null, s2[2]); 
    String[] s3 = parseAuthor("Ginsberg, Allen, kirjoittaja"); 
    assertEquals("From: Util line: 47", "Ginsberg, Allen", s3[0]); 
    assertEquals("From: Util line: 48", null, s3[1]); 
    assertEquals("From: Util line: 49", null, s3[2]); 
  } // Generated by ComTest END
}