package cli.utils.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static cli.utils.Util.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.24 14:20:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UtilTest {



  // Generated by ComTest BEGIN
  /** testSanitizeAuthors18 */
  @Test
  public void testSanitizeAuthors18() {    // Util: 18
    assertEquals("From: Util line: 19", "Austen, Jane", sanitizeAuthors("Austen, Jane, kirjoittaja")); 
    assertEquals("From: Util line: 20", "Burroughs, William S.", sanitizeAuthors("Burroughs, William S., 1914-1997 kirjoittaja")); 
    assertEquals("From: Util line: 21", "Leary, Timothy Francis", sanitizeAuthors("Leary, Timothy Francis, 1920-1996, kirjoittaja Burroughs, William S., 1914-1997, kirjoittaja")); 
  } // Generated by ComTest END
}